### ISSUE TITLE
Conflicting definitions of viewport

### ISSUE THREAD

**Issue by 7--** [mdn/mdn#16]
Here it says: "(the viewport), usually wider than the screen"
https://developer.mozilla.org/en-US/docs/Mozilla/Mobile/Viewport_meta_tag

On this page: "viewport... area in computer graphics that is currently being viewed."
https://developer.mozilla.org/en-US/docs/Glossary/viewport

These statements are mutually exclusive. If a viewport is wider than the screen than it can't only be the portion of the screen that's being viewed. 

Also I'm tying to understand the width value of a viewport but it's not making sense. For the width setting of viewport is says "Defines the pixel width of the viewport, or allows the viewport to adapt to the device's screen width."
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta

But what does that actually mean? It's ambiguous. I don't know what they mean by "define" or what that definition actually does. I thought it could mean set the initial width of the viewport. So I tried setting it to 1 pixel and trying it on a mobile device screen. <meta name="viewport" content="width=1, initial-scale=1"> I was wrong because the page didn't change, showing many more than 1 pixel as the initial width

**Comment by chrisdavidmills** [comment]
I agree that this is rather confusing. I have had a go at rewriting the first article you linked to and third article's width definition.

The first article was sort of correct, but badly worded - it was referring to the "virtual viewport" that mobile browsers use to render pages by default, rather than the actual viewport. See if you thin k my rewrite clears things up for you.

Then the width definition was just badly worded - I've simplified it. Again, let me know if this is better.

**Comment by jwhitlock** [comment]
@7-- If there are additional changes needed, please open a bug on [Bugzilla](https://bugzilla.mozilla.org) against the "Developer Documentation" component.
