### ISSUE TITLE
Collaborator Status on browser-compat-data

### ISSUE THREAD

**Issue by CalmBit** [mdn/mdn#21]
Hello! :smile:
I'm extremely interested in the `browser-compat-data` project, and have enjoyed attempting to contribute to it. I'd love to be more involved and assist with reviewing, if that would be preferable.

**Comment by Elchi3** [comment]
Hi, thanks for your interest in becoming a collaborator and sorry for not coming back to you earlier. 

Reviews can be done in the contributor role as well, so collaborator status isn't needed for that.

In the past, we've been picking very active core contributors ourselves and granted them collaborator status. For browser-compat-data, we currently have a few active Mozilla staffs and contractors who care about the repo. I think once the migration project is done and the schema has stabilized to 1.0.0, we will consider adding collaborators. Right now, many things are still work in progress and need the core staff team to make decisions and merges.

This was filed in February, I remember you being active for a while back then, but I haven't seen you around on the project recently. Thanks for the work you've put into browser-compat-data back then, though. For now, I'm closing this issue here.
