### ISSUE TITLE
Move the BCD collector to MDN GitHub organization

### ISSUE THREAD

**Issue by Elchi3** [mdn/mdn#357]
### Proposal

In the London work week we discussed that the BCD collector project should be moved to the MDN GitHub org.
Right now there are two versions of it:

- https://github.com/foolip/mdn-bcd-collector (this one has a lot more issues that are probably worth keeping and so assume we would move this one)
- https://github.com/GooborgStudios/mdn-bcd-collector (I believe this one is the latest in terms of the code but we can cherry pick those changes later, I assume)

In order to avoid more forks and to have a single repo where we discuss technical design questions and do reviews, we should have a repo where we all contribute to https://github.com/mdn/bcd-collector (or similar).

### Task list

- [ ] Move collector repo to MDN GitHub org
- [ ] Add owners/reviewers

### Additional information

Meeting notes where this was discussed (they are very thin, sorry). https://github.com/openwebdocs/project/blob/main/steering-committee/meetups/london-2023/session-bcd.md 

### Are you willing to support this work?

Yes

### Depends on

cc @foolip @queengooborg @fij

**Comment by queengooborg** [comment]
I discussed this with @LeoMcA a bit more, both in London and after.  Since there is hosting involved, transferring ownership is a little trickier than just transferring the repository, as it would require financial approval for the hosting.  My proposal to mitigate this was that we could transfer the collector repository to MDN ownership, but Gooborg Studios will continue to handle the hosting of the website (at least until Mozilla agrees to host it).

Given this, I think it would actually be better to transfer the newer collector repository (GooborgStudios'/my version).  Although there is a history of issues and pull requests within the original repository, transferring the new repository would ensure a smoother transition with less hosting reconfiguration required.

**Comment by foolip** [comment]
I'm so happy to see this issue, getting the collector into a stable maintenance mode and an "official" part of how BCD is maintained has been my goal all along.

One thing to keep in mind with the two repos is that the commit history has lots of ` (#123)` bits, resulting from merging GitHub PRs. Those will end up linking to the wrong thing from the forked repo:
https://github.com/GooborgStudios/mdn-bcd-collector/commit/04fe53829321a99dcf8240a1dff72bb54fd4d685

The fork would need to pass the issue/PR count of the original repo before these references become unambiguous.

There are also a lot of links to https://github.com/foolip/mdn-bcd-collector issues and PRs from BCD PR discussions, and it would be good if those redirect to the still-maintained copy of the repo.

**Comment by foolip** [comment]
@Rumyra that sounds great, yes! I've sent an email to find a time to meet.

**Comment by caugner** [comment]
Unfortunately, we didn't have the capacity to move the BCD collector into the MDN organization, but we're happy to see that it has found a new home in the [Open Web Docs](https://github.com/openwebdocs/) organization: https://github.com/openwebdocs/mdn-bcd-collector

Therefore I'm closing this issue as resolved.
