### ISSUE TITLE
How to Report Issues?

### ISSUE THREAD

**Issue by pertrai1** [mdn/mdn#39]
I have found an issue where I am not able to get the examples working for `Map`. Here are the examples that are not outputting the same results that are shown in the docs:

Docs: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map
Examples: https://stackblitz.com/edit/js-wul3uj

**Comment by jwhitlock** [comment]
To report content issues, use the menu "Feedback -> Report a Content Issue". This will start the process of opening a bug on Bugzilla.

It appears your issue is with StackBlitz, which is an online development tool for Angular and React apps. 

https://medium.com/@ericsimons/stackblitz-online-vs-code-ide-for-angular-react-7d09348497f4

These frameworks are a lot different than the vanilla JavaScript examples on MDN. The example works for me when I paste it into the Developer Tools - Console window. Most MDN examples will work that way. For an introduction to Firefox's Developer Tools, see https://developer.mozilla.org/en-US/docs/Tools. For other browsers, start with an internet search, like "Developer Tools Edge".

An option for online editing is CodePen.io:

https://codepen.io/jwhitlock/pen/KxXRWX?editors=0011

I hope that helps.
