### ISSUE TITLE
Implement or support the the badging API in Android Mobile browsers.

### ISSUE THREAD

**Issue by 744111** [mdn/mdn#584]
### Proposal

https://developer.mozilla.org/en-US/docs/Web/Progressive_web_apps/How_to/Display_badge_on_app_icon#mobile_support

### The badging API is not supported on Chromium-based browsers running on Android.
```
- if (navigator.setAppBadge) {
  // The API is supported, use it.
} else {
  // The API is not supported, don't use it.
}
```
PWA app is having trouble to set to the Badge count on the Android Mobile Devices. Can we make sure the **navigator.setAppBadge** works in the android Mobile devices?

### Browser support

Currently, it is not supported in any mobile browser version of Android mobile Devices.

### Tasks

- [ ]

### Dependencies

- [ ]

### Are you willing to support this work?

Yes

**Comment by skyclouds2001** [comment]
Don't you think it is something should fire at to browsers, not mdn?

**Comment by bsmth** [comment]
Thanks for opening this one. I believe @skyclouds2001 is correct, if your issue is a feature request, this is not the right place for it, as we're documenting web technologies, not implementing them. I'm going to close for now, but if I've misunderstood, please reply with some more information. Thank you :)
