### ISSUE TITLE
Missing sidebar links for Asynchronous Javascript module in the /learn/javascript section

### ISSUE THREAD

**Issue by BLBaylis** [mdn/mdn#74]
In the sidebar on <a href = "https://developer.mozilla.org/en-US/docs/Learn/JavaScript">this page</a>, and presumably on all other pages with this sidebar, there is no entry for the Asynchronous JavaScript module under JavaScript — Dynamic client-side scripting.  It can be seen in the sidebar of <a href = "https://developer.mozilla.org/en-US/docs/Learn">this section</a> though. 

There is also no reference to it in the sidebar in <a href="https://developer.mozilla.org/en-US/docs/Web/JavaScript">this section.</a>

**Comment by BLBaylis** [comment]
It seems to have been added now

**Comment by wbamberg** [comment]
Sidebars in MDN are implemented using macros, and when the macro changes the page isn't automatically updated: either the platform has to be told to re-render the page, or someone has to force a refresh (which they can do by force-refreshing the page while logged into the site).

I saw your report and force-refreshed, which is why the sidebar looks OK now. But then I forgot to update your issue to explain all this.

So, thanks for filing!
