### ISSUE TITLE
is user-select inherited or not ?

### ISSUE THREAD

**Issue by ghsamm** [mdn/mdn#82]
In the [docs](https://developer.mozilla.org/en-US/docs/Web/CSS/user-select) and [specs](https://drafts.csswg.org/css-ui-4/#propdef-user-select), it is mentioned that `user-select` is **not** inherited. But in practice, precisely in Chrome, it is.

So, which of these is correct ?
* specs are wrong!
* Chrome does not follow specs
* I am wrong about something

Thanks.

**Comment by chrisdavidmills** [comment]
I've tested this too (in Fx/Chrome), and you are right, it does seem to be inherited, which also seems to make sense in terms of expected behavior.

I've added the following note to the `user-select` ref page:

"Note: The spec marks user-select as not being inherited, but in our tests it does seem to be inherited, which makes sense in terms of expected behavior."

It would be nice to find out what is going on here though. @emiliom do you know much about `user-select`, and have you got any thoughts on the above question?

**Comment by chrisdavidmills** [comment]
oops, at-mention was meant for @emilio ;-)

**Comment by emilio** [comment]
No, it's not inherited. Chrome is not following the spec.

See https://github.com/w3c/csswg-drafts/issues/3344. That's what the spec and Firefox implements.

**Comment by emilio** [comment]
So tldr it is _not_ inherited, but the `auto` value, which is the initial value, has the behavior of "propagating" the value for the parent most of the time (unless you're `contenteditable` or an `<input>` / `<textarea>`, etc...)

**Comment by chrisdavidmills** [comment]
@emilio thanks a lot for your help here.
