### ISSUE TITLE
backup plans?

### ISSUE THREAD

**Issue by tomByrer** [mdn/mdn#97]
Seems twitter-sphere is worried about MDN being abandoned.

You have been very gracious in open sourcing all of your tooling & examples, but I can't find any of the source of the docs anywhere?  I'm assuming that it lives in a db on your server?

Sure, a brute-force backup #75 exists, but many of us worry about MDN going down.
Looking for another org took you under their wing? Or thought about leaving the data here to allow someone else help host?

**Comment by peterbe** [comment]
Yes, all the content is stored in a MySQL database in AWS. 
I don't know the finer points for attribution and copyright but it's not inconceivable that we clone that MySQL content to a GitHub repo. We have a bunch of technical aspects of that to figure out (project name: Yari) but most importantly; right now we need to figure out ourselves within Mozilla and how we stand strong despite what's going on. It's certainly complicated because it's not just some code or a blob and we have partners outside of Mozilla too.

**Comment by tomByrer** [comment]
Great to hear that gears are turning!

Praying for you all.

**Comment by ThiefMaster** [comment]
I think having a decentralized (a git repo sounds good) backup is a good place to start. Assuming you now lack some resources to keep things up to date, maybe a git workflow where people can send PRs to update pages (which then automatically update your SQL DB once merged) would awesome to make it easy for people to contribute.

You could even open issues pointing towards thing that need some care - I'm sure there are enough developers out there who wouldn't mind contributing!
