### ISSUE TITLE
Issue in data Types

### ISSUE THREAD

**Issue by GangulyRit** [mdn/mdn#98]
![image](https://user-images.githubusercontent.com/44023607/90134392-bcbfc380-dd8e-11ea-9d6a-17a37cbd35be.png)

See the spec (https://tc39.es/ecma262/#sec-ecmascript-language-types)

Kindly check the issue in data type.

**Comment by peterbe** [comment]
@GangulyRit Do you think you can make an edit to fix it?

**Comment by getify** [comment]
If we're talking about the spec, `function` isn't its own specific type (despite the `typeof` behavior), it's a sub-type of object.

If we're talking about developer ergonomics, `function` is definitely its own type since it has very specific behavior that other object values don't have.

So... it depends.

For the record, the same can be asked of arrays... the spec says they're a subset of object, but they definitely have special behavior we rely on that's different from normal objects.
